export const moviesConstants = {
  SET_MOVIES: "SET_MOVIES",
  SET_SEARCH_FILTER: "SET_SEARCH_FILTER",
  SET_GENRE_FILTER: "SET_GENRE_FILTER",
  SET_RELEASE_YEAR_FILTER: "SET_RELEASE_YEAR_FILTER",
  SET_RATING_FILTER: "SET_RATING_FILTER",
  SET_SHOW_ADD_MOVIE_MODAL: "SET_SHOW_ADD_MOVIE_MODAL",
  ADD_MOVIE: "ADD_MOVIE",
};
